# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd2077c280f838ea8c16a118cd02b0393891ab8393285e47ed29565b0fa89eade93ca5622a47759002580f2c113f7542485c386b83c86b84e1f68796aa496bdd

test:
  secret_key_base: 094ae38abae0544856e5f4a3698191da3b540337fc5dc63fd111fdb60219a50344569697105532a38b838177b52ec86395ae79badd090773f5ab68d68177d9bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
